baseURL = "http://example.org/"
languageCode = "en-us"
title = "maciey's blog."
theme = "cactus"
copyright = "maciey"


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[params]

    show_updated = true # default
    showReadTime = true # default

    description = "I'm that guy that does his job well. And I often fail."

    [[params.social]]
        name = "github"
        link = "https://github.com/macieyng"
    [[params.social]]
        name = "linkedin"
        link = "https://www.linkedin.com/in/macieyn/"
    [[params.social]]
        name = "twitter"
        link = "https://twitter.com/maciey_dev"  # no need for "mailto:" in the head